add role to basecard for upload file
bimdata/platform-old pull request #378
Opened 2019-04-18 15:12 UTC by LrxGaelle

#377

2019-04-18 15:34 UTC, GabBimdata approved these changes

2019-04-23 07:23 UTC, Amoki requested changes

2019-04-23 07:23 UTC, Amoki commented on src/components/project/CardProjectContent.vue
> +        <template v-if="panoramas.length === 0 || isUserRole" slot="content">
`&&`

2019-04-23 13:47 UTC, Amoki approved these changes

2019-04-23 15:37 UTC, merged