Fix/bugs
bimdata/platform-old pull request #386
Opened 2019-04-26 15:37 UTC by LrxGaelle

2019-04-26 15:51 UTC, GabBimdata approved these changes

2019-04-29 08:15 UTC, Amoki requested changes

2019-04-29 08:15 UTC, Amoki commented on src/components/project/DMS.vue
> +                      <li @click="viewIfc(documentAction.item.ifcId)" v-if="documentAction.item.type === 'IFC'">
Can you check on `v-if="documentAction.item.ifc_id" ?
The type may be deprecated someday

2019-04-29 08:39 UTC, Amoki approved these changes

2019-04-29 09:00 UTC, merged