Plateforme - GED problème avec téléchargement d'un dossier
bimdata/platform-old pull request #407
Opened 2019-06-24 16:15 UTC by benjaminaudet

2019-06-25 12:09 UTC, Kurtil requested changes

2019-06-25 12:09 UTC, Kurtil commented on src/components/project/DMS.vue
> +      console.log(documentAction)
Not sure if this line may stay...

2019-06-25 12:54 UTC, benjaminaudet commented on src/components/project/DMS.vue
> +      console.log(documentAction)
oops

2019-06-25 12:55 UTC, benjaminaudet commented on src/components/project/DMS.vue
> +      console.log(documentAction)
done

2019-06-26 12:41 UTC, GabBimdata approved these changes

2019-06-26 12:52 UTC, Amoki approved these changes

2019-06-27 12:51 UTC, Kurtil approved these changes

2019-06-28 12:26 UTC, merged