Fix missing FR translations
bimdata/platform-old pull request #411
Opened 2019-06-26 08:50 UTC by benjaminaudet

2019-06-26 09:15 UTC, mere-teresa requested changes

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +        "creator": "Créateur",
Auteur

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +        "type_to_search": "Entrer du texte pour chercher",
**Saisir** du texte pour **rechercher**

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +        "move_to": "Déplacer dans",
Déplacer **vers**

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +      "clouds_list": "Liste des espaces",
Je mettrais une majuscule à Espace car c'est un "mot du domaine"

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +      "no_creator": "Pas de créateur",
Je n'aime pas trop le terme de "créateur" pour l'auteur d'un fichier. Cela me fait penser : _Dieu est mort ?_

2019-06-26 09:15 UTC, mere-teresa commented on src/lang/fr.json
> +      "modify_rights": "Editer les droits utilisateurs",
Editer les droits **des** utilisateurs

2019-06-26 09:29 UTC, Amoki requested changes
Pendant qu'on est dans la traduction, y'a une faute d'anglais :
Project's clouds (dans le header) devrait être "Cloud's projects"

2019-06-26 09:29 UTC, Amoki commented on src/lang/fr.json
> +        "state": "État",
Si c'est le state d'un IFC (error, completed), je mettrai plutot Status

2019-06-26 09:29 UTC, Amoki commented on src/lang/fr.json
> +      "modify_rights": "Editer les droits utilisateurs",
Editer les droits de l'utilisateur peut être selon le contexte

2019-06-26 09:33 UTC, benjaminaudet commented on src/lang/fr.json
> +      "modify_rights": "Editer les droits utilisateurs",
Effectivement c'est bien "de l'utilisateur" dans le contexte dans lequel on l'utilise

2019-06-26 09:33 UTC, benjaminaudet commented on src/lang/fr.json
> +      "no_creator": "Pas de créateur",
Effectivement auteur me parait mieux même si dans ma tête auteur ça fais vachement bouquin

2019-06-26 09:34 UTC, benjaminaudet commented on src/lang/fr.json
> +      "clouds_list": "Liste des espaces",
J'y ai penser et oui je suis d'accord

2019-06-26 09:35 UTC, benjaminaudet commented on src/lang/fr.json
> +        "state": "État",
Effectivement c'est bien ça, à ce moment là ça s'applique aussi pour l'anglais et au lieu de state on devrait mettre Status aussi

2019-06-26 11:56 UTC, Amoki commented on src/lang/fr.json
> +        "state": "État",
Ok pour status en anglais aussi.

Pendant qu'on est dans la traduction, y'a une faute d'anglais :
Project's clouds (dans le header) devrait être "Cloud's projects"

2019-06-26 12:38 UTC, benjaminaudet commented on src/lang/fr.json
> +        "state": "État",
Je vois pas de quoi tu parles pour Project's clouds, je trouve rien autant sur la plateforme que dans les fichiers de trad concernant ça

2019-06-26 12:38 UTC, benjaminaudet commented on src/lang/fr.json
> +        "state": "État",
Status pour en.json done
b669b895b4e3a161b5ec60df9feb9ea07c5bf555

2019-06-26 13:32 UTC, benjaminaudet commented on src/lang/fr.json
> +        "state": "État",
done

2019-06-27 13:23 UTC, Kurtil approved these changes

2019-06-28 12:35 UTC, merged