Feature/uppy own ui
bimdata/platform-old pull request #438
Opened 2019-08-27 13:55 UTC by benjaminaudet

2019-08-28 08:11 UTC, benjaminaudet commented
Pull request is made, but not ready to be merge, still has changes to be done, like i18n etc

2019-10-07 16:01 UTC, Amoki requested changes

2019-10-07 16:01 UTC, Amoki commented on src/components/project/DMSUploadDocument.vue
> +      debug: true,
debug in production?

2019-10-07 16:01 UTC, Amoki commented on src/components/project/DMSUploadDocument.vue
> +      autoProceed: true,
This change is intentional?

2019-10-07 16:01 UTC, Amoki commented on src/components/project/UploadFile.vue
> +    const endpointUpload = baseApiUrl + '/cloud/' + this.cloudId + '/project/' + this.projectId + '/document'
Template string?

2019-10-07 16:03 UTC, Amoki commented
https://github.com/bimdata/platform/blob/master/index.html#L10 still import old CSS. https://uppy.io/docs/#With-a-module-bundler may be a solution to load CSS cleanly

2021-06-01 12:26 UTC, closed without merging