Add CONTRIBUTING file to the project and ISSUE_TEMPLATE
bimdata/platform-old pull request #449
Opened 2019-09-24 15:53 UTC by mere-teresa

Please review and comment this PR.

2019-09-25 12:47 UTC, Amoki requested changes

2019-09-25 12:47 UTC, Amoki commented on CONTRIBUTING.md
> +* Let the Docker build pass (that verify that your contribution works as expected).
Let the CircleCI build pass

2019-09-25 12:47 UTC, Amoki commented on CONTRIBUTING.md
> +* Run tests:
We don't have tests yet. But you can check if the docker still builds by using `docker build .`

2019-09-25 12:47 UTC, Amoki commented on CONTRIBUTING.md
> +* Maintainers will not review PRs until all checks pass (it means "until Docker builds").
(it means "until CircleCI builds")

2019-09-25 12:47 UTC, Amoki commented on CONTRIBUTING.md
> +* *ALL PULL REQUESTS* should be let the Docker build pass.
CircleCI

2019-09-25 14:23 UTC, mere-teresa commented
I rewrote the CONTRIBUTING file to simplify it.

2019-09-26 14:28 UTC, juliendubost commented on CONTRIBUTING.md
> +If you run into an issue or bug 🐛 with the project, then open an Issue.
C'est quoi le caractère entre "bug" et "with" ?

2019-09-26 14:28 UTC, juliendubost commented on CONTRIBUTING.md
> +Documentation contributions of any size are welcome! Feel free to file a PR even if you're just rewording a sentence to be more clear, or fixing a spelling mistake!
"to file" -> "to fill" ?

2019-09-27 13:22 UTC, mere-teresa commented on CONTRIBUTING.md
> +If you run into an issue or bug 🐛 with the project, then open an Issue.
Un émoji "bug" !  :bug:

2019-09-30 11:29 UTC, Amoki approved these changes

2019-09-30 11:29 UTC, Amoki commented on CONTRIBUTING.md
> +If you run into an issue or bug 🐛 with the project, then open an Issue.
a "bug" emoji

2019-09-30 11:29 UTC, Amoki commented on CONTRIBUTING.md
> +Documentation contributions of any size are welcome! Feel free to file a PR even if you're just rewording a sentence to be more clear, or fixing a spelling mistake!
to file is OK

2019-10-01 08:25 UTC, juliendubost approved these changes

2019-10-01 12:01 UTC, Amoki approved these changes

2019-10-04 09:30 UTC, merged