Add details in the README file for the Platform
bimdata/platform-old pull request #451
Opened 2019-10-02 16:14 UTC by mere-teresa

First steps of a more complete README file.

2019-10-03 08:19 UTC, Amoki requested changes

2019-10-03 08:19 UTC, Amoki commented on README.md
> +git clone git@github.com:bimdata/platform.git
git clone https://github.com/bimdata/platform.git

2019-10-04 12:24 UTC, Amoki approved these changes

2019-10-04 14:33 UTC, LrxGaelle approved these changes

2019-10-04 14:35 UTC, merged