Fix/ged
bimdata/platform-old pull request #477
Opened 2020-02-14 11:01 UTC by LrxGaelle

change width ged & 'import a document' button
 
## Description
- change 'import a document' width into ged
- change width ged and tree view

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2020-02-14 12:49 UTC, Amoki approved these changes

2020-02-14 12:58 UTC, GabBimdata requested changes
![image](https://user-images.githubusercontent.com/32667664/74533472-f889e580-4f31-11ea-9afe-ff85926b6a20.png)
le comportement au resize des pictos ne semble pas ok

2020-02-19 15:49 UTC, GabBimdata approved these changes

2020-02-20 08:32 UTC, Amoki approved these changes

2020-02-20 08:46 UTC, merged